name: Chromatic CD

permissions:
  pull-requests: write
  contents: read

env:
  CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths:
      - packages/moeum-components/**

jobs:
  chromatic-deployment:
    name: Deploy Storybook to Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --filter "./packages/moeum-components" --no-frozen-lockfile

      - name: Publish to Chromatic
        id: chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ env.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/moeum-components

      - name: Add Storybook URL Comment
        uses: thollander/actions-comment-pull-request@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            📚 Storybook is ready for review!
            🔗 Preview: ${{ steps.chromatic.outputs.storybookUrl }}

      - name: Send Slack Success Notification
        if: success()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "✨ **Storybook 배포가 완료되었습니다!** \n\n🔍 PR: ${{ github.event.pull_request.html_url }}\n📚 Storybook: ${{ steps.chromatic.outputs.storybookUrl }}\n\n💬 피드백 부탁드립니다!"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PR_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Send Slack Failure Notification
        if: failure()
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "❌ **Storybook 배포에 실패했습니다!** \n\n🔍 PR: ${{ github.event.pull_request.html_url }}\n\n🚨 확인이 필요합니다."
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_PR_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
